config/routes.rb
Gamenight::Application.routes.draw do

  root 'welcome#index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :filter do
    get 'all' => :all
    get 'cape' => :cape
    get 'tuesday' => :tuesday
  end
  
  get "welcome/index"

  resources :players
  
  resources :nights do
    resources :gameplays, :only => [:new, :create, :destroy]
  end
    
  resources :games do
    resources :win, :only => [:new]
    get '/win_stats' => 'win_stats#show'
  end
  
  resources :users
  

  

end

app/models/night.rb
class Night < ActiveRecord::Base
  validates :date, presence: true, uniqueness: true
  validate :player_count_is_greater_than_two?
  validates_associated :players
  
  has_many :gameplays
  has_and_belongs_to_many :players
  belongs_to :location, class_name: :Player, foreign_key: "location_id"
  belongs_to :night_type
  
  def player_count_is_greater_than_two?
    if player_ids.count < 2
      errors.add(:players, "must have more than #{TextHelper.pluralize player_ids.count, 'player'}")
    end
  end
  
  def finishedCount
    tempCount = 0
    gameplays.each do |gp|
      tempCount += 1 if gp.finished
    end
    tempCount
  end
  
  def uniqueGamesPlayed
    gamesPlayed = [];
    if gameplays.any?
      gameplays.each do |gp|
        if ! gamesPlayed.include?(gp.game.name)
          gamesPlayed << gp.game.name
        end
      end
    else
      gamesPlayed = %w( None )
    end
    return gamesPlayed
  end
  
  scope :tuesday, -> { where(night_type_id: 1) }
  scope :cape, -> { where(night_type_id: 2) }

end

app/models/night_type.rb
class NightType < ActiveRecord::Base
  has_many :nights
end

app/models/score_win.rb
class ScoreWin < ActiveRecord::Base
  has_one :gameplay, :as => :win_info
  has_many :score_win_entries
  has_many :players, through: :score_win_entries
  
  accepts_nested_attributes_for :score_win_entries
  
  def to_partial_path() "win/score_win" end
  
  def ordered
    score_win_entries.sort! { |a,b| b.score <=> a.score }
  end

  def self.win_params (params)
    params.require(:win_info).permit(score_win_entries_attributes: [:player_id, :score ])
  end
end

app/controllers/nights_controller.rb
class NightsController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]
  
  def new
    @night = Night.new
  end
  
  def create
    @night = Night.new(night_params)

    if @night.save
      redirect_to nights_path
    else
      render 'new'
    end
  end
  
  def show
    @night = Night.find(params[:id])
  end
  
  def edit
    @night = Night.find(params[:id])
  end
  
  def update
    @night = Night.find(params[:id])

    @night.assign_attributes(night_params)
    if @night.night_type_id == 2
      @night.location_id = "";
    end

    if @night.save
      redirect_to @night
    else
      render 'edit'
    end
  end
  
  def destroy
    @night = Night.find(params[:id])
    @night.destroy

    redirect_to nights_path
  end
  
  def index
    @nights = Night.all.order("date DESC")
  end
  
  private
    def night_params
      params.require(:night).permit(:date, :location_id, :night_type_id, :player_ids => [])
    end
end

app/helpers/nights_helper.rb
module NightsHelper
  def finishedCount
    tempCount = 0
    @night.gameplays.each do |gp|
      tempCount += 1 if gp.finished
    end
  end
  
  def resetGameplayCounter
    @count = 1
  end
  
  def gameplayCount
    @count
  end
  
  def incGameplayCount
    @count += 1
  end
end

app/views/nights/_form.html.haml
.night_form
  = form_for @night do |f|
    - if @night.errors.any?
      #errorExplanation
        #{pluralize(@night.errors.count, "error")} prohibited this night from being saved:
        %ul
          - @night.errors.full_messages.each do |msg|
            %li= msg
    = f.label :Date
    = f.date_select :date
    #night_type
      = f.label :Type
      = f.select :night_type_id, NightType.all.collect {|x| [x.description, x.id]}
    #night_location
      = f.label :Location
      = f.select :location_id, Player.all.collect {|x| [x.name, x.id]}
    = f.label :Players
    = f.select :player_ids, Player.all.collect {|x| [x.name, x.id]}, {}, :multiple => true
    
    %br
    = f.submit
  :javascript
    $(document).ready(function() {
      night_type_visable()
    });

app/views/nights/_gameplays.html.haml
%h2 Gameplays:
- resetGameplayCounter
.row
  = render(@night.gameplays)

app/views/nights/_night.html.haml
.row#entry
  .span6.well.well-small
    %h3= link_to night.date, night_path(night)
    .gamesplayed
      - night.uniqueGamesPlayed.each do |game|
        .game= game
    .gamecount_line
      %span.count #{night.gameplays.count} (#{night.finishedCount})

app/views/nights/edit.html.haml
%h2 Edit Night
= render 'form'

.links #{link_to 'Back', nights_path}

app/views/nights/index.html.haml
%h2 All the Nights
 
%table
  %tr
    %th Date
    %th
    %th
    %th
 
  - @nights.each do |night|
    %tr
      %td= night.date
      %td= link_to 'Show', night_path(night)
      %td= link_to 'Edit', edit_night_path(night)
      %td= link_to 'Destroy', night_path(night), method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Game Night', new_night_path

app/views/nights/new.html.haml
%h2 New Night
= render 'form'

.links #{link_to 'Back', nights_path}

app/views/nights/show.html.haml
-if notice
  #notice= notice

.date  Date: #{@night.date}

- if @night.location_id
  .location Location: #{@night.location.name}
- else
  .location Location: #{@night.night_type.description}

.players
  Players:
  - @night.players.each do |playah|
    .player_name= playah.name
#gameplays
  = render "gameplays"
  

.row.span12
- if session[:user_id]
  .gameplay_form
    %h4 Add a gameplay:
    #gameplay_notify
    = collection_select(nil, :game_id, Game.all, :id, :name, {:prompt   => "Select a Game"}, {:id => 'game_id'})
    :javascript
      $(document).ready(function() {
        show_gp_info("#{new_night_gameplay_path(@night)}")
      });
    #newgameplay_form

.links #{link_to 'Back', nights_path} | #{link_to 'Edit', edit_night_path(@night)}