config/routes.rb
Gamenight::Application.routes.draw do

  root 'welcome#index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :filter do
    get 'all' => :all
    get 'cape' => :cape
    get 'tuesday' => :tuesday
  end
  
  get "welcome/index"

  resources :players
  
  resources :nights do
    resources :gameplays, :only => [:new, :create, :destroy]
  end
    
  resources :games do
    resources :win, :only => [:new]
    get '/win_stats' => 'win_stats#show'
  end
  
  resources :users
  

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  
  has_many :gameplays
  
  def wins
    game_wins = Array.new;
    gameplays.each do |gp|
      game_wins << gp.win_info if gp.win_info
    end
    game_wins
  end
  
  def finishedCount
    tempCount = 0
    gameplays.each do |gp|
      tempCount += 1 if gp.finished
    end
    tempCount
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]
  
  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new(game_params)

      if @game.save
        redirect_to games_url
      else
        render 'new'
      end
  end
  
  def show
    @game = Game.find(params[:id])
    case @game.win_type
      when "resistance_win"
        @win_stats = ResistanceStats.new(@game.wins)
      when "score_win"
        @win_stats = ScoreStats.new(@game.wins)
      when "normal_win"
        @win_stats = NormalStats.new(@game.wins)
      when "coop_win"
        @win_stats = CoopStats.new(@game.wins)
      else
        raise "Unknown win type, #{win_type}"
      end
  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to game_path
  end
  
  def index
    @games = Game.all
  end
  
  private
    def game_params
      params.require(:game).permit(:name, :win_type)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def getWinTypes
    { "Normal Game" => "normal_win",
      "Score Game" => "score_win",
      "Co-op Game" => "coop_win",
      "Resistance Game" => "resistance_win"
    }
  end
end

app/views/games/_form.html.haml
.game_form
  = form_for @game do |f|
    - if @game.errors.any?
      #errorExplanation
        #{pluralize(@game.errors.count, "error")} prohibited this game from being saved:
        %ul
          - @game.errors.full_messages.each do |msg|
            %li= msg
    = f.label :Game
    = f.text_field :name
    = f.label :Win_Type
    = f.select :win_type, getWinTypes
    %br
    = f.submit

app/views/games/_game.html.haml
%tr
  %td= game.name
  %td Plays: #{game.finishedCount}
  %td.link= link_to 'Details', game_path(game)

app/views/games/edit.html.haml
%h2 Edit Game
= render 'form'

.links #{link_to 'Back', games_path}

app/views/games/index.html.haml
%h2 All the Games
 
%table 
  = render(@games)

- if session[:user_id]
  = link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h2 New Game
= render 'form'

.links #{link_to 'Back', games_path}

app/views/games/show.html.haml
.game 
  Name:
  = @game.name

.wins
  Games played: #{@game.wins.count}
= render partial: @win_stats.partial_name, object: @win_stats

.links #{link_to 'Back', games_path} | #{link_to 'Edit', edit_game_path(@game)}