config/routes.rb
Gamenight::Application.routes.draw do

  root 'welcome#index'

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :filter do
    get 'all' => :all
    get 'cape' => :cape
    get 'tuesday' => :tuesday
  end
  
  get "welcome/index"

  resources :players
  
  resources :nights do
    resources :gameplays, :only => [:new, :create, :destroy]
  end
    
  resources :games do
    resources :win, :only => [:new]
    get '/win_stats' => 'win_stats#show'
  end
  
  resources :users
  

  

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  
  has_and_belongs_to_many :nights
  has_and_belongs_to_many :gameplays
  has_many :locations, class_name: :Night, foreign_key: "location_id"
  
  # resistance play relationships
  has_and_belongs_to_many :spy_plays, class_name: :ResistanceWin, :join_table => :spy_players
  has_and_belongs_to_many :resistance_plays, class_name: :ResistanceWin, :join_table => :resistance_players
  
  # Score win relationship
  has_many :score_win_entries
  has_many :score_wins, through: :score_win_entries
  
  # normal win relationship
  has_many :normal_wins, foreign_key: "winner_id"
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]

  def new
    @player = Player.new
  end
  
  def create
    @player = Player.new(player_params)

      if @player.save
        redirect_to players_url
      else
        render 'new'
      end
  end
  
  def show
    @player = Player.find(params[:id])
  end
  
  def edit
    @player = Player.find(params[:id])
  end
  
  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end
  
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_path
  end
  
  def index
    @players = Player.all
  end
  
  private
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <% if @player.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@player.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Player %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/players/_form.html.haml
.player_form
  = form_for @player do |f|
    - if @player.errors.any?
      #errorExplanation
        #{pluralize(@player.errors.count, "error")} prohibited this player from being saved:
        %ul
          - @player.errors.full_messages.each do |msg|
            %li= msg
    = f.label :Player
    = f.text_field :name
    %br
    = f.submit

app/views/players/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/edit.html.haml
%h2 Edit Player
= render 'form'

.links #{link_to 'Back', players_path}

app/views/players/index.html.erb
<h1>All Players</h1>
 
<table>
  <tr>
    <th>Name</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>
 
  <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= link_to 'Show', player_path(player) %></td>
	  <td><%= link_to 'Edit', edit_player_path(player) %></td>
      <td><%= link_to 'Destroy', player_path(player),
	                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

  <%= link_to 'New player', new_player_path %>
</table>

app/views/players/index.html.haml
%h2 All the Players
 
%table
  %tr
    %th Name
    %th
    %th
    %th
 
  - @players.each do |player|
    %tr
      %td= player.name
      %td= link_to 'Show', player_path(player)
      - if session[:user_id]
        %td= link_to 'Edit', edit_player_path(player)
        %td= link_to 'Destroy', player_path(player), method: :delete, data: { confirm: 'Are you sure?' }

- if session[:user_id]
  = link_to 'New Player', new_player_path

app/views/players/new.html.erb
<h1>New Player</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', players_path %>

app/views/players/new.html.haml
%h2 New Player
= render 'form'

.links #{link_to 'Back', players_path}

app/views/players/show.html.erb
<p>
  <strong>Player:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Back', players_path %> | <%= link_to 'Edit', edit_player_path(@player) %>

app/views/players/show.html.haml
.player 
  Name:
  = @player.name

.links #{link_to 'Back', players_path} | #{link_to 'Edit', edit_player_path(@player)}